apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dreadflix-upload-svc
  template:
    metadata:
      labels:
        app: dreadflix-upload-svc
    spec:
      containers:
      - name: dreadflix-upload-svc
        image: uploadservice.azurecr.io/samples/upload:latest
        ports:
        - containerPort: 3009
---
apiVersion: v1
kind: Service
metadata:
  name: dreadflix-upload-svc
  namespace: default
  labels:
    app: dreadflix-upload-svc
spec:
  selector:
    app: dreadflix-upload-svc
  ports:
    - protocol: TCP
      port: 3009
      targetPort: 3009
  type: LoadBalancer
