apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload-video-service
  template:
    metadata:
      labels:
        app: upload-video-service
    spec:
      containers:
      - name: upload-service
        image: 961341555113.dkr.ecr.us-east-1.amazonaws.com/upload-service:latest
        ports:
        - containerPort: 3009
---
apiVersion: v1
kind: Service
metadata:
  name: upload-video-service
  namespace: default
  labels:
    app: upload-video-service
spec:
  selector:
    app: upload-service
  ports:
    - protocol: TCP
      port: 3009
      targetPort: 3009
  type: NodePort
