apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-permission-checker-binding
subjects:
  - kind: User
    name: "admin"  # Replace with the exact name of the admin user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: permission-checker
  apiGroup: rbac.authorization.k8s.io
