apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: permission-checker
rules:
  - apiGroups: [""]
    resources: ["users"]
    verbs: ["get"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
    verbs: ["get"]
